name: Node.js CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "Backend/package-lock.json"
    - name: Install and build
      working-directory: ./Backend
      run: |
        npm ci
        npm run build --if-present
    - name: es lint check
      working-directory: ./Backend
      run: |
        npm run lint
        npm run typecheck
    - name: Build Docker image
      working-directory: ./Backend
      run: |
        docker build -t nodejs-chess .